/* TEMPLATE PROJECT #2 */

--STEP 1: YOU MUST RUN THE RESEARCH SCRIPT IN [KNOWLEDGE_ARTICLE] BEFORE [REDACTED].

--STEP 2: ENTER THE [REDACTED], [REDACTED], AND [REDACTED] ID.
			--SET @ID4 = 1 AFTER YOU'VE REVIEWED WHETHER THE [REDACTED] IS CONNECTED TO A SYSTEM SETTING.
				--ENSURE YOU'VE REVIEWED ALL [REDACTED] DATA, AND HAVE VERIFIED THAT GENERATING THIS [REDACTED] IS NECESSARY.

DECLARE
		@ID1 INT = 00000	        --THE [REDACTED] THAT [REDACTED] WILL GENERATE INTO
	,	@ID2 INT = 00		        --[REDACTED] ID TO BE GENERATED
	,	@ID3 INT = 000  	    	--[REDACTED] ID TO BE GENERATED
	,	@ID4 BIT = 0	        	--HAVE YOU REVIEWED SYSTEM SETTINGS?
	,	@COMMIT BIT = 0			    --NO GOING BACK WHEN THIS IS SET TO 1

--IF GENERATING [REDACTED]
	,	@ID5 INT = 0		        --ENTER THE [REDACTED] NUMBER (1 OR 2) WHEN GENERATING A [REDACTED] FROM [REDACTED] XX

--ENTER THE FOLLOWING ITEMS WHEN SPECIFIED IN [KNOWLEDGE_ARTICLE].

	,	@ID6 INT = 0	        	--PRIMARY ASSOCIATION BETWEEN THE [REDACTED] AND A [REDACTED], [REDACTED], ETC.
	,	@ID7 INT = 0	        	--THE [REDACTED] OF THE VISIT
	,	@ID8 INT = 0		        --THE [REDACTED] OF THE VISIT
	,	@ID9 INT = 0		        --THIS ASSOCIATES THE [REDACTED] WITH AN [REDACTED]

-----------------------------------------------------
-------------DO NOT EDIT BELOW THIS LINE-------------
-----------------------------------------------------
	,	@ID5CHECKER INT
	,	@ID10 BIT

	SET @ID10 = (SELECT 1 FROM TABLE_NAME ALIAS1 WHERE ID_1 = @ID1 AND ID_2 = 'EXAMPLE')

BEGIN 

	DECLARE @SQLQUERY NVARCHAR(MAX)
		,	@SQLQUERYEND NVARCHAR(MAX)
		,	@SQLPARAMS NVARCHAR(MAX)
		,	@SQLPOSTVALIDATIONS NVARCHAR(MAX)
		,	@SQLEOP NVARCHAR(MAX)
		,	@SQLERRORCATCH NVARCHAR(MAX)

	--VALIDATIONS

	IF (@ID1 !> 0 OR @ID2 !> 0 OR @ID3 !> 0)

		BEGIN
			SET @COMMIT = 0
			SELECT 'ID_1, ID_2, AND ID_3 MUST BE DECLARED.' as [VALIDATION], 'PLEASE REVIEW.' AS [MESSAGE]
			RETURN
		END

	IF @COMMIT = 1 AND @ID4 = 0

		BEGIN
			SET @COMMIT = 0
			SELECT 'PLEASE CONFIRM SYSTEM SETTINGS HAVE BEEN REVIEWED.' AS [ACTION REQUIRED]
			RETURN
		END

	IF @ID2 = 70 AND @ID5 NOT IN (1,2)

		BEGIN
			SET @COMMIT = 0
			SELECT 'PLEASE DECLARE A VALID [REDACTED].' AS [ACTION REQUIRED]
			RETURN
		END

	IF @ID10 = 1

		BEGIN
			SET @COMMIT = 0
			SELECT 'THIS IS A EXAMPLE_TYPE [REDACTED].' AS [ROLLED BACK]
			RETURN
		END

	--GENERATE
	SET @SQLQUERY = 
	'BEGIN TRAN TEMPLATEPROJECTNUM02

	DECLARE @RETURN_VALUE INT,
	@ID11 INT

	BEGIN TRY

	EXEC @RETURN_VALUE = [DBO].[STORED_PROC] --WE USE THE OLD VERSION OF THIS PROC TO PREVENT (SOME_DATA))
	@ID_01 = @ID1,
	@ID_02 = @ID2,
	@ID_03 = @ID3,
	'

	SET @SQLQUERYEND =
	'
	@ID11 = @ID11 OUTPUT

	SELECT @ID11 AS N''NEW @ID11 GENERATED'', ''IF NULL, NOTHING GENERATED'' AS [MESSAGE]

	SELECT ''ERROR? (SHOULD BE 0)'' = @RETURN_VALUE
	'

	SET @SQLEOP = 
	'
	IF @ID2 = XX

					BEGIN

						IF EXISTS(
						           SELECT 1 
								   FROM TABLE_NAME2
								   JOIN TABLE_NAME3
									  ON FK_2 = PK_3
								   WHERE FK2_2 = @ID1
								   AND PK3_1 = @ID5
								   AND FK3_1 = 1
								  )

							BEGIN
								SET @COMMIT = 0
								SELECT ''THIS IS A DELETED PERIOD.'' AS [VALIDATION], ''PLEASE REVIEW.'' AS [ROLLED BACK]
							END

						SET @ID5CHECKER = (SELECT ID_1 
											  FROM TABLE_NAME3
											  JOIN TABLE_NAME2 ALIAS2
											     ON FK3_1 = ALIAS2.PK
											  JOIN TABLE_NAME4 ALIAS4 
											     ON ALIS4.FK = ALIAS2.FK
											  JOIN TABLE_NAME5 ALIAS5 
											     ON ALIAS5.FK = ALIAS4.PK
											  JOIN TABLE_NAME6 ALIAS6 
											     ON ALIAS6.FK = ALIS5.PK
											  WHERE ALIAS6.FK = @ID11
											  AND ALIAS6.FK2 = ALIAS2_PK
											 )

						IF NOT EXISTS(
									  SELECT 1 
									  FROM TABLENAME6 ALIAS6 
									  WHERE ALIAS6.FK = @ID11
									  AND ALIAS6.FK3 = 602
									 )

							BEGIN
								INSERT INTO TABLE_NAME6 
								VALUES (@ID11, 602, (SELECT ALIAS3.PK
													   FROM TABLE_NAME3 ALIAS3
													   JOIN TABLE_NAME2 ALIAS2 
													      ON ALIAS3.FK = ALIAS2.PK
													   WHERE ALIAS2.FK = @ID1
													   AND ALIAS3.FK = @ID5
													  )
									   )
							END

						IF @ID5CHECKER <> @ID5

							BEGIN
								UPDATE TABLE_NAME6 
								SET TABLE_NAME6.FK = (SELECT ALIAS3.PK
													 FROM TABLE_NAME3 ALIAS3
													 JOIN TABLE_NAME2 ALIAS2 
													     ON ALIAS3.FK = ALIAS2.PK
												     WHERE ALIAS2.FK = @ID1
													 AND ALIAS3.FK = @ID5
													)
								WHERE TABLE_NAME6.FK = @ID11
								SELECT @@ROWCOUNT AS [[REDACTED] UPDATED SUCCESSFULLY]
							END

					END
	'

	SET @SQLERRORCATCH =
	'
	IF @ID11 IS NULL

		BEGIN
			SELECT ''IF NOTHING GENERATED, REVIEW [REDACTED] DOC AND [REDACTED] DATA.'' AS [VALIDATION MESSAGE]

			ROLLBACK
			RETURN
		END

	END TRY

	BEGIN CATCH
		SELECT CONCAT(''ERROR: '', ERROR_MESSAGE()) AS [DO NOT COMMIT!]
		SELECT ''TRIAGE TO [REDACTED] IF [TYPE] [REDACTED] NEEDS TO BE GENERATED'' AS [VALIDATION]
		
		ROLLBACK 
		RETURN
	END CATCH
	'

	SET @SQLPOSTVALIDATIONS =
	'
		BEGIN

			SELECT CASE WHEN TABLE_NAME5.PK = @ID11 THEN ''IF COMMITTED -->'' ELSE '''' END AS [[REDACTED] [REDACTED]], 
			TABLE_NAME5.PK, TABLE_NAME7.FK, TABLE_NAME4.FK [EVID], TABLE_NAME5.FK [STID],
			TABLE_NAME5.FK, TABLE_NAME5.FK, TABLE_NAME5.FK, TABLE_NAME5.FK [REPORTPARAM]
			, TABLE_NAME5.FK [ENDED], TABLE_NAME5.FK [ACTIVE], TABLE_NAME5.FK
			, TABLE_NAME5.FK, (SELECT FK1 FROM TABLE_NAME8 ALIAS8 WHERE FK1 = TABLE_NAME5.FK) [FK1]
			FROM DBO.TABLE_NAME5 ALIAS5
			JOIN DBO.TABLE_NAME4 ALIAS4 ON ALIAS4.PK = ALIAS5.FK
			JOIN DBO.TABLE_NAME7 ALIAS7 ON ALIAS7.PK = ALIAS5.FK
			WHERE ALIAS4.FK = @ID1
			AND ALIAS4.PK = @ID2
			ORDER BY ALIAS5.FK, ALIAS4.FK

			IF EXISTS(
			           SELECT 1 
					   FROM [DBO].TABLE_NAME6 
					   WHERE TABLE_NAME6.FK = @ID11
					 )

			SELECT ALIAS6.FK1, ALIAS6.FK2, TABLE_NAME9.FK1, TABLE_NAME9.FK2
			FROM [DBO]. TABLE_NAME6 ALIAS6
			JOIN [DBO]. TABLE_NAME9 ON TABLE_NAME9.PK = ALIAS6.FK 
			WHERE ALIAS6.FK = @ID11

		END
	'

	IF @ID6 > 0 AND @ID8 = 0

		BEGIN
			SET @SQLQUERY = @SQLQUERY + '
			@ID6ETER = @ID6,'
		END

	IF @ID6 > 0 AND @ID8 > 0

		BEGIN
			SET @SQLQUERY = @SQLQUERY + '
			@ID6ETER = @ID8,'
		END

	IF @ID7 > 0

		BEGIN 
			SET @SQLQUERY = @SQLQUERY + '
			@ID7ID = @ID7,'
		END

	IF @ID9 > 0

		BEGIN
			SET @SQLQUERY = @SQLQUERY + '
			@ID_04 = @ID9,'
		END

	--NOW ADD THE REST OF THE QUERY
	SET @SQLQUERY = @SQLQUERY + @SQLQUERYEND + @SQLEOP + @SQLERRORCATCH + @SQLPOSTVALIDATIONS

	--COMMIT FLAG
	SET @SQLQUERY = @SQLQUERY + 
		(
		CASE WHEN @COMMIT = 1 
		THEN 
			'
			COMMIT TRAN TEMPLATEPROJECTNUM02
			SELECT ''LAND OF NO RETURN'' AS [COMMITTED]
			'
		ELSE
			'
			ROLLBACK TRAN TEMPLATEPROJECTNUM02
			SELECT ''NO CHANGES MADE'' AS [ROLLED BACK], ''SET COMMIT BIT = 1 AND RUN AGAIN'' AS [IF THERE ARE NO ERRORS]
			'
		END
		)

--DECLARING PARAMETERS
SET @SQLPARAMS = '
	@ID1 INT
,	@ID2 INT
,	@ID3 INT
,	@ID6 INT
,	@ID7 INT
,	@ID8 INT
,	@ID9 INT
,	@ID5 INT
,	@ID5CHECKER INT
,	@COMMIT BIT'

--EXECUTE QUERY
EXECUTE SP_EXECUTESQL
			@SQLQUERY
		,	@SQLPARAMS
		,	@ID1
		,	@ID2 
		,	@ID3
		,	@ID6
		,	@ID7
		,	@ID8
		,	@ID9
		,	@ID5
		,	@ID5CHECKER
		,	@COMMIT

END
